name: "\U0001F4DD Request a change (not rule-related)"
description: "Request a change that is not a bug fix, rule change, or new rule"
title: "Change Request: (fill in)"
labels:
    - enhancement
    - triage
    - core
body:
    - type: markdown
      attributes:
          value: By opening an issue, you agree to abide by the [Open JS Foundation Code of Conduct](https://eslint.org/conduct).
    - type: input
      attributes:
          label: ec0lint version
          description: |
              What version of ec0lint are you currently using? (Run `npx ec0lint --version`.)
          placeholder: |
              e.g. v1.0.0
      validations:
          required: true
    - type: textarea
      attributes:
          label: What problem do you want to solve?
          description: |
              Please explain your use case in as much detail as possible.
          placeholder: |
              ec0lint currently...
      validations:
          required: true
    - type: textarea
      attributes:
          label: What do you think is the correct solution?
          description: |
              Please explain how you'd like to change ec0lint to address the problem.
          placeholder: |
              I'd like ec0lint to...
      validations:
          required: true
    - type: checkboxes
      attributes:
          label: Participation
          options:
              - label: I am willing to submit a pull request for this change.
                required: false
    - type: textarea
      attributes:
          label: Additional comments
          description: Is there anything else that's important for the team to know?
