reportUnusedDisableDirectives: true
extends:
    - "ec0lint:recommended"

rules:
   avoid-lodash: "error"
   lighter-http: "error"
   lighter-image-files": "error"
   lighter-video-files": "error"
   no-ajax-events: "error"
   no-ajax: "error"
   no-animate: "error"
   no-attr: "error"
   no-autoplay": "error"
   no-bind: "error"
   no-browser: "error"
   no-box-model: "error"
   no-date-fns: "error"
   no-moment-js: "error"
