reportUnusedDisableDirectives: true
extends:
    - "ec0lint:recommended"

rules:
   lighter-http: "error"
   no-ajax: "error"
   avoid-lodash: "error"
   no-ajax-events: "error"
   no-and-self: "error"
   no-bind: "error"
   no-date-fns: "error"
   no-moment-js: "error"
   lighter-video-files: "error"
   lighter-image-files: "error"
